### PR TITLE
Dev sida quickfix autodetect gpu arch

### PR DESCRIPTION
**Pull request by liusida**
Copied CMakeLists.txt from the future.

No need for tag `-DCMAKE_BUILD_TYPE=Release` and `-DCUDA_DEBUG=OFF`, those are by default now.

### CODE REVIEW

**Comment by davidmatthews1uvm** [comment]
The cmake file contains references to the new collision system which is not yet merged into master.

**Comment by liusida** [comment]
removed. please review again.

**Review by davidmatthews1uvm — APPROVED** [review]
Looks good.

**Review by skriegman — APPROVED** [review]
:+1:

**Pull request merged**
